# プロジェクトのメタ情報
[project]
name = "python-template"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aws-opentelemetry-distro>=0.19.0",
    "awscrt>=0.36.2",
    "boto3>=1.43.88",
    "strands-agents>=1.54.0",
    "strands-agents-tools>=0.8.7",
]

# 開発環境でのみ利用するパッケージ
[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "ruff",
]

# pytest
[tool.pytest.ini_options]
pythonpath = ["src"]

# ruff
[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
